export const SET_STATUSBAR_HEIGHT = 'SET_STATUSBAR_HEIGHT';
export const SET_STATUSBAR_STYLE = 'SET_STATUSBAR_STYLE';
export const SET_NETINFO = 'SET_NETINFO';

export const SET_IS_ONBOARDING = 'SET_IS_ONBOARDING';
export const SET_PAGE_LOADING = 'SET_PAGE_LOADING';
export const SET_UPLOADING = 'SET_UPLOADING';
export const RESTART_UPLOADING = 'RESTART_UPLOADING';

export const SET_SAVED_EXAMS = 'SET_SAVED_EXAMS';
export const SET_SUBMITTED_EXAMS = 'SET_SUBMITTED_EXAMS';

export const SET_CURRENT_EXAM = 'SET_CURRENT_EXAM';
export const SET_CURRENT_EXAM_UUID = 'SET_CURRENT_EXAM_UUID';
export const SET_EXAM_MEDIA_TYPE = 'SET_EXAM_MEDIA_TYPE';

export const SET_TESTED_VIDEO = 'SET_TESTED_VIDEO';

export const SET_EXAM_INFO = 'SET_EXAM_INFO';
export const UPDATE_EXAM_INFO = 'UPDATE_EXAM_INFO';
export const UPDATE_EXAM_PIECE = 'UPDATE_EXAM_PIECE';
export const DELETE_EXAM_PIECE = 'DELETE_EXAM_PIECE';
export const ADD_EXAM_PIECE = 'ADD_EXAM_PIECE';

export const UPDATE_UPLOADING_STATUS = 'UPDATE_UPLOADING_STATUS';

export const SET_RECORDING_CLIPS = 'SET_RECORDING_CLIPS';
export const ADD_RECORDING_CLIP = 'ADD_RECORDING_CLIP';
export const UPDATE_RECORDING_CLIP_INFO = 'UPDATE_RECORDING_CLIP_INFO';
export const REMOVE_RECORDING_CLIP = 'REMOVE_RECORDING_CLIP';

export const DELETE_EXAM = 'DELETE_EXAM';

export const SET_SELECTED_SUBMITTED_EXAM_ID = 'SET_SELECTED_SUBMITTED_EXAM_ID';